version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      - 'POSTGRES_DB=SpringVendor'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=oiler'
      - 'POSTGRES_URL=jdbc:postgresql://postgres:5432/SpringVendor'
    ports:
      - "5433:5432"
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
