name: Deploy to Azure VM

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script: |
            docker stop vendor || true
            docker rm vendor || true

            docker pull ${{ secrets.ACR_LOGIN_SERVER }}/vendor:latest

            docker run -d --name vendor \
              --restart unless-stopped \
              -p 8081:8081 \
              -e "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" \
              -e "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
              -e "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
              -e "SPRING_DATA_MONGODB_URI=${{ secrets.SPRING_DATA_MONGODB_URI }}" \
              -e "SUPPLIER_ID=${{ secrets.SUPPLIER_ID }}" \
              ${{ secrets.ACR_LOGIN_SERVER }}/vendor:latest
