name: Test, Upload artifact and Deploy to Container
on:
  workflow_dispatch:
#  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 22 ]
    name: Run unit tests on Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - run: mvn -f pom.xml clean compile test
  build-deploy:
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        java: [ 22 ]
    name: Build and Publish Docker Image
    steps:
      - uses: actions/checkout@v4
      - name: Build java app
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'adopt'
      - name: Build and package project
        run: mvn -f pom.xml clean package

      - name: build the docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/vendor:latest

      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: push the docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/vendor:latest